let inv = [
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  },
  {
    company: ["mj seeds canada"],
    price: [],
    effect: [],
    yield: [],
    flowerTime: [],
    relations: [],
    pThc: [],
    pCbd: [],
    pCbn: [],
    country: [],
    name: "",
    description: "",
    genetic: 0,
    difficulty: 0,
    indica: 0,
    sativa: 0,
    ruderalis: 0,
    type: 0,
    environment: 0,
    sotiId: "",
    sttId: "",
    releaseDate: "2018-06-01T07:00:00.000Z",
    isFeatured: false
  }
];
